modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="darkestsouls"
version="1.1.0.1"
displayName="Darkest Souls"
authors="Nitespring"

description='''Miyazaki's Dirty Socks'''

[[dependencies.darkestsouls]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.0-beta,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.darkestsouls]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.darkestsouls]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.5.5,)"
    ordering="NONE"
    side="BOTH"
